import { useCallback, useEffect, useState } from "react";
import * as api from "./lib/api";
import type { DockerContainer, DistroResourceInfo, PortInfo, WslDistro } from "./lib/types";
import "./App.css";

type Page = "Dashboard" | "Machines" | "Docker" | "Settings" | "Detail";
const Status = ({ state }: { state: string }) => <span className={`status ${state.toLowerCase()}`}>● {state}</span>;
function App() {
  const [page, setPage] = useState<Page>("Dashboard"), [distros, setDistros] = useState<WslDistro[]>([]), [selected, setSelected] = useState<WslDistro>(), [error, setError] = useState(""), [confirm, setConfirm] = useState(false);
  const refresh = useCallback(async () => { try { setDistros(await api.listWslDistros()); setError(""); } catch (e) { setError(String(e)); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const goDetail = (d: WslDistro) => { setSelected(d); setPage("Detail"); };
  const body = page === "Dashboard" ? <Dashboard distros={distros} /> : page === "Machines" ? <Machines distros={distros} refresh={refresh} select={goDetail} error={setError} /> : page === "Docker" ? <Docker distros={distros} error={setError} /> : page === "Settings" ? <Settings /> : selected ? <Detail distro={selected} error={setError} /> : null;
  return <div className="shell"><aside><div className="brand"><b>WSL</b> Dev Center</div><nav>{(["Dashboard", "Machines", "Docker", "Settings"] as Page[]).map((p) => <button className={page === p || page === "Detail" && p === "Machines" ? "active" : ""} onClick={() => setPage(p)} key={p}>{p}</button>)}</nav></aside><main><header><div><span className="eyebrow">LOCAL WORKSPACE</span><h1>{page === "Detail" ? selected?.name : page}</h1></div>{page === "Machines" && <button className="danger" onClick={() => setConfirm(true)}>Shutdown all WSL</button>}</header>{error && <div className="error"><strong>Operation failed</strong><br />{error}</div>}{body}{confirm && <div className="dialog"><section role="alertdialog"><h2>Shutdown all WSL?</h2><p>This will stop all running WSL distributions. Continue?</p><footer><button autoFocus onClick={() => setConfirm(false)}>Cancel</button> <button className="danger" onClick={() => { setConfirm(false); void api.shutdownWsl().then(refresh).catch((e) => setError(String(e))); }}>Shutdown WSL</button></footer></section></div>}</main></div>;
}
function Dashboard({ distros }: { distros: WslDistro[] }) { const running = distros.filter((d) => d.state === "Running").length; return <><section className="hero"><span className="eyebrow">WSL DEVELOPMENT ENVIRONMENTS</span><h2>Know what is running.<br />Control only what you need.</h2><p className="muted">A local control surface for WSL, ports, and Docker.</p></section><section className="metrics">{[["Running", running], ["Stopped", distros.filter((d) => d.state === "Stopped").length], ["Distributions", distros.length], ["Docker", "On demand"]].map(([k, v]) => <article className="metric" key={String(k)}><span>{k}</span><strong>{v}</strong></article>)}</section></>; }
function Machines({ distros, refresh, select, error }: { distros: WslDistro[]; refresh: () => Promise<void>; select: (d: WslDistro) => void; error: (v: string) => void }) { const run = async (fn: () => Promise<unknown>) => { try { await fn(); await refresh(); } catch (e) { error(String(e)); } }; return <section className="panel"><div className="toolbar"><h2>Distributions</h2><button onClick={() => void refresh()}>Refresh</button></div>{!distros.length ? <p className="muted">No WSL distributions found. Install one with <code>wsl --install</code>.</p> : <div className="table"><table><thead><tr><th>Name</th><th>State</th><th>Version</th><th>Default</th><th>Actions</th></tr></thead><tbody>{distros.map((d) => <tr key={d.name}><td>{d.name}</td><td><Status state={d.state} /></td><td>WSL {d.version ?? "—"}</td><td>{d.isDefault ? "Default" : "—"}</td><td className="actions"><button onClick={() => void run(() => d.state === "Stopped" ? api.startDistro(d.name) : api.terminateDistro(d.name))}>{d.state === "Stopped" ? "Start" : "Stop"}</button><button onClick={() => void run(() => api.restartDistro(d.name))}>Restart</button><button onClick={() => void run(() => api.openTerminal(d.name))}>Terminal</button><button onClick={() => void run(() => api.openHome(d.name))}>Files</button><button onClick={() => void run(() => api.openVscode(d.name))}>VS Code</button><button onClick={() => select(d)}>Details</button></td></tr>)}</tbody></table></div>}</section>; }
function Detail({ distro, error }: { distro: WslDistro; error: (v: string) => void }) { const [resource, setResource] = useState<DistroResourceInfo>(), [portList, setPorts] = useState<PortInfo[]>([]), [docker, setDocker] = useState<DockerContainer[]>([]); const load = async (what: "resource" | "ports" | "docker") => { try { if (what === "resource") setResource(await api.resources(distro.name)); if (what === "ports") setPorts(await api.ports(distro.name)); if (what === "docker") setDocker(await api.containers(distro.name)); } catch (e) { error(String(e)); } }; useEffect(() => { void load("resource"); }, [distro.name]); return <><section className="panel"><div className="detail"><h2>{distro.name} <Status state={distro.state} /></h2><button onClick={() => void load("resource")}>Refresh overview</button></div><div className="resource">{[["Memory", resource?.memoryText], ["Disk", resource?.diskText], ["Uptime", resource?.uptimeText], ["Processes", resource?.processCount]].map(([k, v]) => <article key={String(k)}><span>{k}</span><strong>{String(v || "Unavailable")}</strong></article>)}</div></section><section className="panel"><div className="toolbar"><h2>Listening ports</h2><button onClick={() => void load("ports")}>Refresh ports</button></div><PortRows ports={portList} /></section><section className="panel"><div className="toolbar"><h2>Docker containers</h2><button onClick={() => void load("docker")}>Refresh Docker</button></div>{docker.length ? <div className="table"><table><thead><tr><th>Name</th><th>Image</th><th>Status</th><th>Ports</th></tr></thead><tbody>{docker.map((c) => <tr key={c.id}><td>{c.names}</td><td>{c.image}</td><td>{c.status}</td><td>{c.ports ?? "—"}</td></tr>)}</tbody></table></div> : <p className="muted">Docker not found, or no containers in this distribution.</p>}</section></>; }
function Docker({ distros, error }: { distros: WslDistro[]; error: (v: string) => void }) { const [name, setName] = useState(""), [items, setItems] = useState<DockerContainer[]>([]); const load = async (v: string) => { setName(v); if (!v) return; try { setItems(await api.containers(v)); } catch (e) { error(`Docker is not installed in this distribution. ${String(e)}`); } }; return <section className="panel"><h2>Docker by distribution</h2><p className="muted">Only the selected distribution is inspected.</p><select value={name} onChange={(e) => void load(e.target.value)}><option value="">Choose a running distribution</option>{distros.filter((d) => d.state === "Running").map((d) => <option key={d.name}>{d.name}</option>)}</select>{items.length > 0 && <p>{items.length} containers found.</p>}</section>; }
function PortRows({ ports }: { ports: PortInfo[] }) { return ports.length ? <div className="table"><table><thead><tr><th>Protocol</th><th>Address</th><th>Port</th><th>Process</th><th>PID</th><th /></tr></thead><tbody>{ports.map((p) => <tr key={p.raw}><td>{p.protocol}</td><td>{p.localAddress}</td><td>{p.port}</td><td>{p.processName ?? "—"}</td><td>{p.pid ?? "—"}</td><td><button onClick={() => navigator.clipboard.writeText(`localhost:${p.port}`)}>Copy</button></td></tr>)}</tbody></table></div> : <p className="muted">No listening ports found.</p>; }
function Settings() { const [refresh, setRefresh] = useState(localStorage.getItem("refresh") ?? "5"); useEffect(() => localStorage.setItem("refresh", refresh), [refresh]); return <section className="panel"><h2>Local settings</h2><label>Refresh interval <select value={refresh} onChange={(e) => setRefresh(e.target.value)}><option value="0">Manual</option><option value="3">3 seconds</option><option value="5">5 seconds</option><option value="10">10 seconds</option></select></label><p className="muted">Preferences stay in localStorage; they are never synced.</p></section>; }
export default App;
